//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class LocalFrameSynServerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("LocalFrameSynServer");
		L.RegFunction("Start", Start);
		L.RegFunction("SynFrameData", SynFrameData);
		L.RegFunction("SendPlayerOperation", SendPlayerOperation);
		L.RegFunction("LuaSendPlayerOperation", LuaSendPlayerOperation);
		L.RegFunction("LuaSendCameraTouch", LuaSendCameraTouch);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Start(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			LocalFrameSynServer.Start();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SynFrameData(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			LocalFrameSynServer.SynFrameData();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SendPlayerOperation(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			FrameSynchronOperationType arg0 = (FrameSynchronOperationType)ToLua.CheckObject(L, 1, typeof(FrameSynchronOperationType));
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
			string arg2 = ToLua.CheckString(L, 3);
			LocalFrameSynServer.SendPlayerOperation(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LuaSendPlayerOperation(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 1);
			int arg1 = (int)LuaDLL.luaL_checknumber(L, 2);
			string arg2 = ToLua.CheckString(L, 3);
			LocalFrameSynServer.LuaSendPlayerOperation(arg0, arg1, arg2);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LuaSendCameraTouch(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			float arg0 = (float)LuaDLL.luaL_checknumber(L, 1);
			float arg1 = (float)LuaDLL.luaL_checknumber(L, 2);
			LocalFrameSynServer.LuaSendCameraTouch(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

