--[[ M-模型表.xlsm 模型表
[n] : 模型ID
strSkinName : 模型文件名称
modelScale : 模型缩放比例
strAction0 : 动作0
strAction1 : 动作1
]]
return {
[1] = { strSkinName='Assets/Res/Prefabs/CommEmptyObj.prefab', modelScale=1000, strAction0='', strAction1='', },
[2] = { strSkinName='Assets/Res/Prefabs/NpcEmptyObj.prefab', modelScale=800, strAction0='', strAction1='', },
[3] = { strSkinName='Assets/Res/Prefabs/NpcEmptyObj.prefab', modelScale=1000, strAction0='', strAction1='', },
[4] = { strSkinName='Assets/Res/Prefabs/NpcEmptyObj.prefab', modelScale=1500, strAction0='', strAction1='', },
[17] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_HuoChe.prefab', modelScale=1000, strAction0='', strAction1='', },
[18] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_JiJiaBao_White.prefab', modelScale=1000, strAction0='', strAction1='', },
[19] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_JiJiaBao_Red.prefab', modelScale=1000, strAction0='', strAction1='', },
[20] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_JiJiaBao_Blue.prefab', modelScale=1000, strAction0='', strAction1='', },
[21] = { strSkinName='Assets/Res/Prefabs/Component/Body/RobotPartBody_XiaoHongChe.prefab', modelScale=1000, strAction0='', strAction1='', },
[22] = { strSkinName='Assets/Res/Prefabs/Component/Move/Move_Wheel_4.prefab', modelScale=1000, strAction0='', strAction1='', },
[101] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Test1.prefab', modelScale=1000, strAction0='', strAction1='', },
[102] = { strSkinName='Assets/Res/Prefabs/RobotPartHoleModel.prefab', modelScale=1000, strAction0='', strAction1='', },
[103] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Test11.prefab', modelScale=1000, strAction0='', strAction1='', },
[1001] = { strSkinName='Assets/Res/Prefabs/RobotPartFragment/Chariot03_lingjian_01.prefab', modelScale=1000, strAction0='', strAction1='', },
[1002] = { strSkinName='Assets/Res/Prefabs/RobotPartFragment/Chariot03_lingjian_02.prefab', modelScale=1000, strAction0='', strAction1='', },
[1003] = { strSkinName='Assets/Res/Prefabs/RobotPartFragment/Chariot03_lingjian_03.prefab', modelScale=1000, strAction0='', strAction1='', },
[1004] = { strSkinName='Assets/Res/Prefabs/RobotPartFragment/Chariot03_lingjian_04.prefab', modelScale=1000, strAction0='', strAction1='', },
--//主体},
[10000] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Z_Yellow.prefab', modelScale=1000, strAction0='', strAction1='', },
[10001] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Z_Brown.prefab', modelScale=1000, strAction0='', strAction1='', },
[10002] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Z_Black.prefab', modelScale=1000, strAction0='', strAction1='', },
[10003] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Z_Blue.prefab', modelScale=1000, strAction0='', strAction1='', },
[10004] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Z_Green.prefab', modelScale=1000, strAction0='', strAction1='', },
[10005] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Z_Green.prefab', modelScale=1000, strAction0='', strAction1='', },
[10100] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_8_Green.prefab', modelScale=1000, strAction0='', strAction1='', },
[10101] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_8_Red.prefab', modelScale=1000, strAction0='', strAction1='', },
[10102] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_8_Yellow.prefab', modelScale=1000, strAction0='', strAction1='', },
[10103] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_8_Blue.prefab', modelScale=1000, strAction0='', strAction1='', },
[10200] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_JiJiaBao_White.prefab', modelScale=1000, strAction0='', strAction1='', },
[10300] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_CircleDaYan.prefab', modelScale=1000, strAction0='', strAction1='', },
[10301] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_CircleJiXie.prefab', modelScale=1000, strAction0='', strAction1='', },
[10302] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_NiuJiJia.prefab', modelScale=1000, strAction0='Assets/Res/Role/Animation/Body_niujijia/jixieniu_stand.anim', strAction1='Assets/Res/Role/Animation/Body_niujijia/Body_niujijia_attack.anim', },
[10303] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Test2.prefab', modelScale=1000, strAction0='', strAction1='', },
[10304] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Test3.prefab', modelScale=1000, strAction0='', strAction1='', },
[10305] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Test4.prefab', modelScale=1000, strAction0='', strAction1='', },
[10306] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Test5.prefab', modelScale=1000, strAction0='', strAction1='', },
[10307] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Test6.prefab', modelScale=1000, strAction0='', strAction1='', },
[10308] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Test7.prefab', modelScale=1000, strAction0='', strAction1='', },
[10309] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Test8.prefab', modelScale=1000, strAction0='', strAction1='', },
[10310] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Test9.prefab', modelScale=1000, strAction0='', strAction1='', },
[10311] = { strSkinName='Assets/Res/Prefabs/Component/Body/Body_Test10.prefab', modelScale=1000, strAction0='', strAction1='', },
--//攻击},
[20100] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Saw_MonsterL.prefab', modelScale=1000, strAction0='', strAction1='', },
[20101] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Saw_MonsterR.prefab', modelScale=1000, strAction0='', strAction1='', },
[20102] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Saw_BossL.prefab', modelScale=1000, strAction0='', strAction1='', },
[20103] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Saw_BossR.prefab', modelScale=1000, strAction0='', strAction1='', },
[20104] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Saw_F.prefab', modelScale=1000, strAction0='', strAction1='', },
[20105] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Saw_L.prefab', modelScale=1000, strAction0='', strAction1='', },
[20106] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Saw_R.prefab', modelScale=1000, strAction0='', strAction1='', },
[20200] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Cannon_Monster.prefab', modelScale=1000, strAction0='', strAction1='', },
[20201] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Tailgunner_Red.prefab', modelScale=1000, strAction0='', strAction1='', },
[20202] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Cannon_Boss.prefab', modelScale=1000, strAction0='', strAction1='', },
[20203] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Cannon.prefab', modelScale=1000, strAction0='', strAction1='', },
[20204] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Tailgunner_Black.prefab', modelScale=1000, strAction0='', strAction1='', },
[20300] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Awl_L.prefab', modelScale=1000, strAction0='', strAction1='', },
[20301] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Awl_R.prefab', modelScale=1000, strAction0='', strAction1='', },
[20400] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Hammer.prefab', modelScale=1000, strAction0='', strAction1='', },
[20500] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Spring_L.prefab', modelScale=1000, strAction0='', strAction1='', },
[20501] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Spring_R.prefab', modelScale=1000, strAction0='', strAction1='', },
[20502] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Spring_BossL.prefab', modelScale=1000, strAction0='', strAction1='', },
[20503] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Spring_BossR.prefab', modelScale=1000, strAction0='', strAction1='', },
[20600] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Gun_MonsterL.prefab', modelScale=1000, strAction0='', strAction1='', },
[20601] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Gun_MonsterR.prefab', modelScale=1000, strAction0='', strAction1='', },
[20602] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Gun_L.prefab', modelScale=1000, strAction0='', strAction1='', },
[20603] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_Gun_R.prefab', modelScale=1000, strAction0='', strAction1='', },
[20604] = { strSkinName='Assets/Res/Prefabs/Component/Weapon/Weapon_NiuJiJiaSpring.prefab', modelScale=1000, strAction0='', strAction1='', },
--//移动},
[30100] = { strSkinName='Assets/Res/Prefabs/Component/Move/Move_Wheel_4.prefab', modelScale=1000, strAction0='', strAction1='', },
[30101] = { strSkinName='Assets/Res/Prefabs/Component/Move/Move_Wheel_3.prefab', modelScale=1000, strAction0='', strAction1='', },
[30200] = { strSkinName='Assets/Res/Prefabs/Component/Move/Move_Maglev.prefab', modelScale=1000, strAction0='', strAction1='', },
[30300] = { strSkinName='Assets/Res/Prefabs/Component/Move/Move_Cricle_1.prefab', modelScale=1000, strAction0='', strAction1='', },
[30301] = { strSkinName='Assets/Res/Prefabs/Component/Move/Move_Cricle_2.prefab', modelScale=1000, strAction0='', strAction1='', },
[30302] = { strSkinName='Assets/Res/Prefabs/Component/Move/Move_Cricle_4.prefab', modelScale=1000, strAction0='', strAction1='', },
[30303] = { strSkinName='Assets/Res/Prefabs/Component/Move/Move_Cricle_3.prefab', modelScale=1000, strAction0='', strAction1='', },
[30400] = { strSkinName='Assets/Res/Prefabs/Component/Move/Move_Machine.prefab', modelScale=1000, strAction0='', strAction1='', },
[30401] = { strSkinName='Assets/Res/Prefabs/Component/Move/Move_Leg.prefab', modelScale=1000, strAction0='', strAction1='', },
--//辅助},
[40100] = { strSkinName='Assets/Res/Prefabs/Component/Assist/Assist_Nitrogen.prefab', modelScale=1000, strAction0='', strAction1='', },
[40101] = { strSkinName='Assets/Res/Prefabs/Component/Assist/Assist_Nitrogen_Boss.prefab', modelScale=1000, strAction0='', strAction1='', },
[40200] = { strSkinName='Assets/Res/Prefabs/Component/Assist/Assist_Erduo_L.prefab', modelScale=1000, strAction0='', strAction1='', },
[40201] = { strSkinName='Assets/Res/Prefabs/Component/Assist/Assist_Erduo_R.prefab', modelScale=1000, strAction0='', strAction1='', },
[40300] = { strSkinName='Assets/Res/Prefabs/Component/Assist/Assist_Shovel.prefab', modelScale=1000, strAction0='', strAction1='', },
[40400] = { strSkinName='Assets/Res/Prefabs/Component/Assist/Assist_Thruser.prefab', modelScale=1000, strAction0='', strAction1='', },
[40500] = { strSkinName='Assets/Res/Prefabs/Component/Assist/Assist_Reject.prefab', modelScale=1000, strAction0='', strAction1='', },
[40501] = { strSkinName='Assets/Res/Prefabs/Component/Assist/Assist_Reject.prefab', modelScale=1000, strAction0='', strAction1='', },
[40600] = { strSkinName='Assets/Res/Prefabs/Component/Assist/Assist_Shield.prefab', modelScale=1000, strAction0='', strAction1='', },
[40700] = { strSkinName='Assets/Res/Prefabs/Component/Assist/Assist_Split_Boss.prefab', modelScale=1000, strAction0='', strAction1='', },
}