// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace behaviac
{
	public class CompareValue_BehaviacGameEvent : ICompareValue<BehaviacGameEvent>
	{
		public override bool Equal(BehaviacGameEvent lhs, BehaviacGameEvent rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(BehaviacGameEvent lhs, BehaviacGameEvent rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(BehaviacGameEvent lhs, BehaviacGameEvent rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(BehaviacGameEvent lhs, BehaviacGameEvent rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(BehaviacGameEvent lhs, BehaviacGameEvent rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(BehaviacGameEvent lhs, BehaviacGameEvent rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_BehaviacCallType : ICompareValue<BehaviacCallType>
	{
		public override bool Equal(BehaviacCallType lhs, BehaviacCallType rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(BehaviacCallType lhs, BehaviacCallType rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(BehaviacCallType lhs, BehaviacCallType rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(BehaviacCallType lhs, BehaviacCallType rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(BehaviacCallType lhs, BehaviacCallType rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(BehaviacCallType lhs, BehaviacCallType rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_BehaviacNpcAttrType : ICompareValue<BehaviacNpcAttrType>
	{
		public override bool Equal(BehaviacNpcAttrType lhs, BehaviacNpcAttrType rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(BehaviacNpcAttrType lhs, BehaviacNpcAttrType rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(BehaviacNpcAttrType lhs, BehaviacNpcAttrType rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(BehaviacNpcAttrType lhs, BehaviacNpcAttrType rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(BehaviacNpcAttrType lhs, BehaviacNpcAttrType rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(BehaviacNpcAttrType lhs, BehaviacNpcAttrType rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_BehaviacNpcAttrValGetType : ICompareValue<BehaviacNpcAttrValGetType>
	{
		public override bool Equal(BehaviacNpcAttrValGetType lhs, BehaviacNpcAttrValGetType rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(BehaviacNpcAttrValGetType lhs, BehaviacNpcAttrValGetType rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(BehaviacNpcAttrValGetType lhs, BehaviacNpcAttrValGetType rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(BehaviacNpcAttrValGetType lhs, BehaviacNpcAttrValGetType rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(BehaviacNpcAttrValGetType lhs, BehaviacNpcAttrValGetType rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(BehaviacNpcAttrValGetType lhs, BehaviacNpcAttrValGetType rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_BehaviacNpcAttrValSetType : ICompareValue<BehaviacNpcAttrValSetType>
	{
		public override bool Equal(BehaviacNpcAttrValSetType lhs, BehaviacNpcAttrValSetType rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(BehaviacNpcAttrValSetType lhs, BehaviacNpcAttrValSetType rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(BehaviacNpcAttrValSetType lhs, BehaviacNpcAttrValSetType rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(BehaviacNpcAttrValSetType lhs, BehaviacNpcAttrValSetType rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(BehaviacNpcAttrValSetType lhs, BehaviacNpcAttrValSetType rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(BehaviacNpcAttrValSetType lhs, BehaviacNpcAttrValSetType rhs)
		{
			return lhs <= rhs;
		}
	}

	public class CompareValue_BehaviacSkillDoStageType : ICompareValue<BehaviacSkillDoStageType>
	{
		public override bool Equal(BehaviacSkillDoStageType lhs, BehaviacSkillDoStageType rhs)
		{
			return lhs == rhs;
		}
		public override bool NotEqual(BehaviacSkillDoStageType lhs, BehaviacSkillDoStageType rhs)
		{
			return lhs != rhs;
		}
		public override bool Greater(BehaviacSkillDoStageType lhs, BehaviacSkillDoStageType rhs)
		{
			return lhs > rhs;
		}
		public override bool GreaterEqual(BehaviacSkillDoStageType lhs, BehaviacSkillDoStageType rhs)
		{
			return lhs >= rhs;
		}
		public override bool Less(BehaviacSkillDoStageType lhs, BehaviacSkillDoStageType rhs)
		{
			return lhs < rhs;
		}
		public override bool LessEqual(BehaviacSkillDoStageType lhs, BehaviacSkillDoStageType rhs)
		{
			return lhs <= rhs;
		}
	}


	public class BehaviorLoaderImplement : BehaviorLoader
	{
		private class CMethod_behaviac_Agent_VectorAdd : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorAdd()
			{
			}

			public CMethod_behaviac_Agent_VectorAdd(CMethod_behaviac_Agent_VectorAdd rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorAdd(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorAdd((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorClear : CAgentMethodVoidBase
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorClear()
			{
			}

			public CMethod_behaviac_Agent_VectorClear(CMethod_behaviac_Agent_VectorClear rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorClear(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				behaviac.Agent.VectorClear((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorContains : CAgentMethodBase<bool>
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorContains()
			{
			}

			public CMethod_behaviac_Agent_VectorContains(CMethod_behaviac_Agent_VectorContains rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorContains(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				_returnValue.value = behaviac.Agent.VectorContains((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorLength : CAgentMethodBase<int>
		{
			IInstanceMember _param0;

			public CMethod_behaviac_Agent_VectorLength()
			{
			}

			public CMethod_behaviac_Agent_VectorLength(CMethod_behaviac_Agent_VectorLength rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorLength(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 1);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);

				_returnValue.value = behaviac.Agent.VectorLength((IList)_param0.GetValueObject(self));
			}
		}

		private class CMethod_behaviac_Agent_VectorRemove : CAgentMethodVoidBase
		{
			IInstanceMember _param0;
			IInstanceMember _param1;

			public CMethod_behaviac_Agent_VectorRemove()
			{
			}

			public CMethod_behaviac_Agent_VectorRemove(CMethod_behaviac_Agent_VectorRemove rhs) : base(rhs)
			{
			}

			public override IMethod Clone()
			{
				return new CMethod_behaviac_Agent_VectorRemove(this);
			}

			public override void Load(string instance, string[] paramStrs)
			{
				Debug.Check(paramStrs.Length == 2);

				_instance = instance;
				_param0 = AgentMeta.ParseProperty<IList>(paramStrs[0]);
				_param1 = AgentMeta.ParseProperty<System.Object>(paramStrs[1]);
			}

			public override void Run(Agent self)
			{
				Debug.Check(_param0 != null);
				Debug.Check(_param1 != null);

				behaviac.Agent.VectorRemove((IList)_param0.GetValueObject(self), (System.Object)_param1.GetValueObject(self));
			}
		}


		public override bool Load()
		{
			AgentMeta.TotalSignature = 3143439282;

			AgentMeta meta;

			// behaviac.Agent
			meta = new AgentMeta(24743406);
			AgentMeta._AgentMetas_[2436498804] = meta;
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { behaviac.Agent.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());

			// BaseBehaviac
			meta = new AgentMeta(3175532143);
			AgentMeta._AgentMetas_[3824313761] = meta;
			meta.RegisterMethod(517719448, new CAgentMethodVoid<bool>(delegate(Agent self, bool bSuc) { ((BaseBehaviac)self).MapLevelEnd(bSuc); }));
			meta.RegisterMethod(333712300, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nBuffCfgId) { ((BaseBehaviac)self).NpcBuffAdd(nNpcInstId, nBuffCfgId); }));
			meta.RegisterMethod(1960930834, new CAgentMethod<int, int, int>(delegate(Agent self, int nNpcInstId, int nEffId) { return ((BaseBehaviac)self).AddNpcBodyEffect(nNpcInstId, nEffId); }));
			meta.RegisterMethod(1043635382, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nBuffCfgId) { ((BaseBehaviac)self).NpcBuffRemove(nNpcInstId, nBuffCfgId); }));
			meta.RegisterMethod(1252178389, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nTreatmentPercent) { ((BaseBehaviac)self).NpcTreatmentPercentInput(nNpcInstId, nTreatmentPercent); }));
			meta.RegisterMethod(1465201290, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nTreatmentVal) { ((BaseBehaviac)self).NpcTreatmentInput(nNpcInstId, nTreatmentVal); }));
			meta.RegisterMethod(3784053026, new CAgentMethod<int, List<int>>(delegate(Agent self, List<int> pArrayInt) { return ((BaseBehaviac)self).GetRandomIdxByWeight(pArrayInt); }));
			meta.RegisterMethod(2033743707, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((BaseBehaviac)self).IsNpcDead(nNpcInstId); }));
			meta.RegisterMethod(2728183447, new CAgentMethod<string>(delegate(Agent self) { return ((BaseBehaviac)self).GetCurCallTreeName(); }));
			meta.RegisterMethod(2045082202, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((BaseBehaviac)self).IsLevelNpcAllEnableByName0(nNameId); }));
			meta.RegisterMethod(3443252747, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((BaseBehaviac)self).GetLevelNpcAllDead0(nNameId); }));
			meta.RegisterMethod(3080141289, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((BaseBehaviac)self).IsLevelTrapAllEnableByName0(nNameId); }));
			meta.RegisterMethod(471432746, new CAgentMethod<bool, int>(delegate(Agent self, int nIdx) { return ((BaseBehaviac)self).GetEventParamBool(nIdx); }));
			meta.RegisterMethod(1398363131, new CAgentMethod<int, int>(delegate(Agent self, int nIdx) { return ((BaseBehaviac)self).GetEventParamInt(nIdx); }));
			meta.RegisterMethod(779082234, new CAgentMethod<string, int>(delegate(Agent self, int nIdx) { return ((BaseBehaviac)self).GetEventParamString(nIdx); }));
			meta.RegisterMethod(4133508887, new CAgentMethod<int, int, int>(delegate(Agent self, int nMin, int nMax) { return ((BaseBehaviac)self).GetRandomValByRange(nMin, nMax); }));
			meta.RegisterMethod(3645314284, new CAgentMethod<int>(delegate(Agent self) { return ((BaseBehaviac)self).GetPlayerNpcInstId(); }));
			meta.RegisterMethod(3163466376, new CAgentMethod<bool>(delegate(Agent self) { return ((BaseBehaviac)self).IsPlayerNpcDead(); }));
			meta.RegisterMethod(3372771259, new CAgentMethod<int>(delegate(Agent self) { return ((BaseBehaviac)self).GetFrameSynRunTime(); }));
			meta.RegisterMethod(2963145510, new CAgentMethodVoid<int>(delegate(Agent self, int nEffInstId) { ((BaseBehaviac)self).DelEffect(nEffInstId); }));
			meta.RegisterMethod(3718685615, new CAgentMethodVoid<int, bool>(delegate(Agent self, int nNameId, bool bEnable) { ((BaseBehaviac)self).SetLevelNpcEnableByName0(nNameId, bEnable); }));
			meta.RegisterMethod(1559481390, new CAgentMethodVoid<int, bool>(delegate(Agent self, int nNameId, bool nEnable) { ((BaseBehaviac)self).SetLevelTrapEnableByName0(nNameId, nEnable); }));
			meta.RegisterMethod(1672556066, new CAgentMethod<bool, int, int>(delegate(Agent self, int nNpcInstId, int nPercentVal) { return ((BaseBehaviac)self).IsNpcLastPercentHp(nNpcInstId, nPercentVal); }));
			meta.RegisterMethod(3109641221, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((BaseBehaviac)self).IsMonsterNpc(nNpcInstId); }));
			meta.RegisterMethod(3158467113, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((BaseBehaviac)self).IsBuildNpc(nNpcInstId); }));
			meta.RegisterMethod(96586450, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((BaseBehaviac)self).IsPlayerNpc(nNpcInstId); }));
			meta.RegisterMethod(3719375762, new CAgentMethod<bool, BehaviacCallType>(delegate(Agent self, BehaviacCallType eType) { return ((BaseBehaviac)self).IsCurCallType(eType); }));
			meta.RegisterMethod(1865017882, new CAgentMethod<bool, BehaviacGameEvent>(delegate(Agent self, BehaviacGameEvent eType) { return ((BaseBehaviac)self).IsTargetGameEvent(eType); }));
			meta.RegisterMethod(326959891, new CAgentMethodVoid<string, int, int, int, int, int>(delegate(Agent self, string sString, int nInt0, int nInt1, int nInt2, int nInt3, int nInt4) { ((BaseBehaviac)self).PrintLog(sString, nInt0, nInt1, nInt2, nInt3, nInt4); }));
			meta.RegisterMethod(1376336015, new CAgentMethod<int, int, string>(delegate(Agent self, int nCfgId, string sPointName) { return ((BaseBehaviac)self).AddNpcToMapByPoint(nCfgId, sPointName); }));
			meta.RegisterMethod(3067532362, new CAgentMethod<int, int, float, float, float, float, float, float>(delegate(Agent self, int nCfgId, float nPosX, float nPosY, float nPosZ, float nRotX, float nRotY, float nRotZ) { return ((BaseBehaviac)self).AddNpcToMapByPos(nCfgId, nPosX, nPosY, nPosZ, nRotX, nRotY, nRotZ); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { BaseBehaviac.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());
			meta.RegisterMethod(4023451816, new CAgentMethodVoid<List<int>>(delegate(Agent self, List<int> taskArrayIntRef) { }) /* TaskArrayIntRef */);

			// NpcBehaviac
			meta = new AgentMeta(2901341239);
			AgentMeta._AgentMetas_[717162176] = meta;
			meta.RegisterMemberProperty(4238705584, new CMemberProperty<int>("BuffCfgId", delegate(Agent self, int value) {  }, delegate(Agent self) { return ((NpcBehaviac)self).BuffCfgId; }));
			meta.RegisterMemberProperty(2357565195, new CMemberProperty<int>("NpcInstId", delegate(Agent self, int value) {  }, delegate(Agent self) { return ((NpcBehaviac)self).NpcInstId; }));
			meta.RegisterMemberProperty(4216888273, new CMemberProperty<int>("ViewRange", delegate(Agent self, int value) {  }, delegate(Agent self) { return ((NpcBehaviac)self).ViewRange; }));
			meta.RegisterMethod(209606860, new CAgentMethodVoid<bool>(delegate(Agent self, bool bAdd) { ((NpcBehaviac)self).ReturnBuffIsCanAdd(bAdd); }));
			meta.RegisterMethod(2159718507, new CAgentMethod<int>(delegate(Agent self) { return ((NpcBehaviac)self).GetBuffLayer(); }));
			meta.RegisterMethod(517719448, new CAgentMethodVoid<bool>(delegate(Agent self, bool bSuc) { ((NpcBehaviac)self).MapLevelEnd(bSuc); }));
			meta.RegisterMethod(333712300, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nBuffCfgId) { ((NpcBehaviac)self).NpcBuffAdd(nNpcInstId, nBuffCfgId); }));
			meta.RegisterMethod(1960930834, new CAgentMethod<int, int, int>(delegate(Agent self, int nNpcInstId, int nEffId) { return ((NpcBehaviac)self).AddNpcBodyEffect(nNpcInstId, nEffId); }));
			meta.RegisterMethod(1043635382, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nBuffCfgId) { ((NpcBehaviac)self).NpcBuffRemove(nNpcInstId, nBuffCfgId); }));
			meta.RegisterMethod(1252178389, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nTreatmentPercent) { ((NpcBehaviac)self).NpcTreatmentPercentInput(nNpcInstId, nTreatmentPercent); }));
			meta.RegisterMethod(1465201290, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nTreatmentVal) { ((NpcBehaviac)self).NpcTreatmentInput(nNpcInstId, nTreatmentVal); }));
			meta.RegisterMethod(3784053026, new CAgentMethod<int, List<int>>(delegate(Agent self, List<int> pArrayInt) { return ((NpcBehaviac)self).GetRandomIdxByWeight(pArrayInt); }));
			meta.RegisterMethod(2033743707, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((NpcBehaviac)self).IsNpcDead(nNpcInstId); }));
			meta.RegisterMethod(2728183447, new CAgentMethod<string>(delegate(Agent self) { return ((NpcBehaviac)self).GetCurCallTreeName(); }));
			meta.RegisterMethod(2045082202, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((NpcBehaviac)self).IsLevelNpcAllEnableByName0(nNameId); }));
			meta.RegisterMethod(3443252747, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((NpcBehaviac)self).GetLevelNpcAllDead0(nNameId); }));
			meta.RegisterMethod(3080141289, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((NpcBehaviac)self).IsLevelTrapAllEnableByName0(nNameId); }));
			meta.RegisterMethod(471432746, new CAgentMethod<bool, int>(delegate(Agent self, int nIdx) { return ((NpcBehaviac)self).GetEventParamBool(nIdx); }));
			meta.RegisterMethod(1398363131, new CAgentMethod<int, int>(delegate(Agent self, int nIdx) { return ((NpcBehaviac)self).GetEventParamInt(nIdx); }));
			meta.RegisterMethod(779082234, new CAgentMethod<string, int>(delegate(Agent self, int nIdx) { return ((NpcBehaviac)self).GetEventParamString(nIdx); }));
			meta.RegisterMethod(4133508887, new CAgentMethod<int, int, int>(delegate(Agent self, int nMin, int nMax) { return ((NpcBehaviac)self).GetRandomValByRange(nMin, nMax); }));
			meta.RegisterMethod(3645314284, new CAgentMethod<int>(delegate(Agent self) { return ((NpcBehaviac)self).GetPlayerNpcInstId(); }));
			meta.RegisterMethod(3163466376, new CAgentMethod<bool>(delegate(Agent self) { return ((NpcBehaviac)self).IsPlayerNpcDead(); }));
			meta.RegisterMethod(3372771259, new CAgentMethod<int>(delegate(Agent self) { return ((NpcBehaviac)self).GetFrameSynRunTime(); }));
			meta.RegisterMethod(2963145510, new CAgentMethodVoid<int>(delegate(Agent self, int nEffInstId) { ((NpcBehaviac)self).DelEffect(nEffInstId); }));
			meta.RegisterMethod(3718685615, new CAgentMethodVoid<int, bool>(delegate(Agent self, int nNameId, bool bEnable) { ((NpcBehaviac)self).SetLevelNpcEnableByName0(nNameId, bEnable); }));
			meta.RegisterMethod(1559481390, new CAgentMethodVoid<int, bool>(delegate(Agent self, int nNameId, bool nEnable) { ((NpcBehaviac)self).SetLevelTrapEnableByName0(nNameId, nEnable); }));
			meta.RegisterMethod(1672556066, new CAgentMethod<bool, int, int>(delegate(Agent self, int nNpcInstId, int nPercentVal) { return ((NpcBehaviac)self).IsNpcLastPercentHp(nNpcInstId, nPercentVal); }));
			meta.RegisterMethod(3109641221, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((NpcBehaviac)self).IsMonsterNpc(nNpcInstId); }));
			meta.RegisterMethod(3158467113, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((NpcBehaviac)self).IsBuildNpc(nNpcInstId); }));
			meta.RegisterMethod(96586450, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((NpcBehaviac)self).IsPlayerNpc(nNpcInstId); }));
			meta.RegisterMethod(3719375762, new CAgentMethod<bool, BehaviacCallType>(delegate(Agent self, BehaviacCallType eType) { return ((NpcBehaviac)self).IsCurCallType(eType); }));
			meta.RegisterMethod(1865017882, new CAgentMethod<bool, BehaviacGameEvent>(delegate(Agent self, BehaviacGameEvent eType) { return ((NpcBehaviac)self).IsTargetGameEvent(eType); }));
			meta.RegisterMethod(326959891, new CAgentMethodVoid<string, int, int, int, int, int>(delegate(Agent self, string sString, int nInt0, int nInt1, int nInt2, int nInt3, int nInt4) { ((NpcBehaviac)self).PrintLog(sString, nInt0, nInt1, nInt2, nInt3, nInt4); }));
			meta.RegisterMethod(1376336015, new CAgentMethod<int, int, string>(delegate(Agent self, int nCfgId, string sPointName) { return ((NpcBehaviac)self).AddNpcToMapByPoint(nCfgId, sPointName); }));
			meta.RegisterMethod(3067532362, new CAgentMethod<int, int, float, float, float, float, float, float>(delegate(Agent self, int nCfgId, float nPosX, float nPosY, float nPosZ, float nRotX, float nRotY, float nRotZ) { return ((NpcBehaviac)self).AddNpcToMapByPos(nCfgId, nPosX, nPosY, nPosZ, nRotX, nRotY, nRotZ); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { NpcBehaviac.LogMessage(param0); }));
			meta.RegisterMethod(503894485, new CAgentMethod<bool, int, int>(delegate(Agent self, int nNpcInstId, int nRange) { return ((NpcBehaviac)self).IsInRangeOfNpc(nNpcInstId, nRange); }));
			meta.RegisterMethod(2383000211, new CAgentMethod<int, BehaviacNpcAttrType, BehaviacNpcAttrValGetType>(delegate(Agent self, BehaviacNpcAttrType nType, BehaviacNpcAttrValGetType nValType) { return ((NpcBehaviac)self).NpcAttrGet(nType, nValType); }));
			meta.RegisterMethod(1366454875, new CAgentMethodVoid<BehaviacNpcAttrType, BehaviacNpcAttrValSetType, int>(delegate(Agent self, BehaviacNpcAttrType nType, BehaviacNpcAttrValSetType nValType, int nVal) { ((NpcBehaviac)self).NpcAttrSet(nType, nValType, nVal); }));
			meta.RegisterMethod(2211159813, new CAgentMethodVoid<BehaviacNpcAttrType, BehaviacNpcAttrValSetType, int>(delegate(Agent self, BehaviacNpcAttrType nType, BehaviacNpcAttrValSetType nValType, int nVal) { ((NpcBehaviac)self).NpcAttrModfiy(nType, nValType, nVal); }));
			meta.RegisterMethod(2841194716, new CAgentMethod<int>(delegate(Agent self) { return ((NpcBehaviac)self).GetEnemyNpcInView(); }));
			meta.RegisterMethod(268857142, new CAgentMethod<bool, int>(delegate(Agent self, int nPartCfgId) { return ((NpcBehaviac)self).IsRobotPartExistAndLive(nPartCfgId); }));
			meta.RegisterMethod(1859141242, new CAgentMethod<float>(delegate(Agent self) { return ((NpcBehaviac)self).GetRotX(); }));
			meta.RegisterMethod(2009796411, new CAgentMethod<float>(delegate(Agent self) { return ((NpcBehaviac)self).GetRotY(); }));
			meta.RegisterMethod(1558600952, new CAgentMethod<float>(delegate(Agent self) { return ((NpcBehaviac)self).GetRotZ(); }));
			meta.RegisterMethod(2917706264, new CAgentMethod<int>(delegate(Agent self) { return ((NpcBehaviac)self).GetSelfNpcInstId(); }));
			meta.RegisterMethod(291470239, new CAgentMethod<float>(delegate(Agent self) { return ((NpcBehaviac)self).GetPosX(); }));
			meta.RegisterMethod(138693342, new CAgentMethod<float>(delegate(Agent self) { return ((NpcBehaviac)self).GetPosY(); }));
			meta.RegisterMethod(594090269, new CAgentMethod<float>(delegate(Agent self) { return ((NpcBehaviac)self).GetPosZ(); }));
			meta.RegisterMethod(974251282, new CAgentMethod<bool, int>(delegate(Agent self, int nPartCfgId) { return ((NpcBehaviac)self).NpcPartIsDead(nPartCfgId); }));
			meta.RegisterMethod(1985082778, new CAgentMethodVoid<bool>(delegate(Agent self, bool bEnable) { ((NpcBehaviac)self).SetPauseState(bEnable); }));
			meta.RegisterMethod(782852143, new CAgentMethod<bool, int>(delegate(Agent self, int nVague) { return ((NpcBehaviac)self).IsLookAtPlayer(nVague); }));
			meta.RegisterMethod(4150835748, new CAgentMethod<bool, int, int>(delegate(Agent self, int nNpcInstId, int nVague) { return ((NpcBehaviac)self).IsLookAtNpc(nNpcInstId, nVague); }));
			meta.RegisterMethod(1923390963, new CAgentMethod<bool, int, int>(delegate(Agent self, int nAngle, int nDistance) { return ((NpcBehaviac)self).IsCanMoveToPlace(nAngle, nDistance); }));
			meta.RegisterMethod(4072845582, new CAgentMethod<bool, int>(delegate(Agent self, int nPercent) { return ((NpcBehaviac)self).IsLastPercentHp(nPercent); }));
			meta.RegisterMethod(2943224411, new CAgentMethod<bool, int>(delegate(Agent self, int nPartCfgId) { return ((NpcBehaviac)self).NpcIsHaveRobotPart(nPartCfgId); }));
			meta.RegisterMethod(2634551815, new CAgentMethod<bool, int>(delegate(Agent self, int nRange) { return ((NpcBehaviac)self).IsInRangeOfPlayerNpc(nRange); }));
			meta.RegisterMethod(1385441514, new CAgentMethod<bool, int, int>(delegate(Agent self, int nNpcInstId, int nDistance) { return ((NpcBehaviac)self).MoveToNpcByDistance(nNpcInstId, nDistance); }));
			meta.RegisterMethod(493907768, new CAgentMethod<bool, int>(delegate(Agent self, int nDistance) { return ((NpcBehaviac)self).MoveToPlayerByDistance(nDistance); }));
			meta.RegisterMethod(580498949, new CAgentMethod<bool, int>(delegate(Agent self, int nAngle) { return ((NpcBehaviac)self).MoveToAngle(nAngle); }));
			meta.RegisterMethod(258853777, new CAgentMethod<bool>(delegate(Agent self) { return ((NpcBehaviac)self).MoveToSpawnPositon(); }));
			meta.RegisterMethod(3823470545, new CAgentMethod<bool>(delegate(Agent self) { return ((NpcBehaviac)self).MoveToPlayer(); }));
			meta.RegisterMethod(2856849106, new CAgentMethod<bool, int, int, int>(delegate(Agent self, int nNpcInstId, int nAngle, int nDistance) { return ((NpcBehaviac)self).MoveToRelativeNpcDirect(nNpcInstId, nAngle, nDistance); }));
			meta.RegisterMethod(1990783130, new CAgentMethod<bool, int, int>(delegate(Agent self, int nAngle, int nDistance) { return ((NpcBehaviac)self).MoveToRelativePlayerDirect(nAngle, nDistance); }));
			meta.RegisterMethod(3541156698, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((NpcBehaviac)self).MoveToNpc(nNpcInstId); }));
			meta.RegisterMethod(1743900358, new CAgentMethod<bool, string>(delegate(Agent self, string sPointName) { return ((NpcBehaviac)self).MoveToPoint(sPointName); }));
			meta.RegisterMethod(3202624698, new CAgentMethod<bool, int, int>(delegate(Agent self, int nAngle, int nDistance) { return ((NpcBehaviac)self).MoveToPlace(nAngle, nDistance); }));
			meta.RegisterMethod(1047467498, new CAgentMethod<bool, float, float, float>(delegate(Agent self, float nPosX, float nPosY, float nPosZ) { return ((NpcBehaviac)self).MoveToPos(nPosX, nPosY, nPosZ); }));
			meta.RegisterMethod(4133893578, new CAgentMethod<bool>(delegate(Agent self) { return ((NpcBehaviac)self).IsMoveReach(); }));
			meta.RegisterMethod(299907559, new CAgentMethodVoid(delegate(Agent self) { ((NpcBehaviac)self).MoveStop(); }));
			meta.RegisterMethod(3070884759, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((NpcBehaviac)self).TurnToNpc(nNpcInstId); }));
			meta.RegisterMethod(3617192099, new CAgentMethod<bool>(delegate(Agent self) { return ((NpcBehaviac)self).TurnToSpawnPositon(); }));
			meta.RegisterMethod(833076035, new CAgentMethod<bool, string>(delegate(Agent self, string sPointName) { return ((NpcBehaviac)self).TurnToPoint(sPointName); }));
			meta.RegisterMethod(2457734407, new CAgentMethod<bool>(delegate(Agent self) { return ((NpcBehaviac)self).IsTurnReach(); }));
			meta.RegisterMethod(1651520766, new CAgentMethodVoid(delegate(Agent self) { ((NpcBehaviac)self).TurnStop(); }));
			meta.RegisterMethod(2120328715, new CAgentMethod<bool>(delegate(Agent self) { return ((NpcBehaviac)self).TurnToPlayer(); }));
			meta.RegisterMethod(3904002367, new CAgentMethod<bool, int>(delegate(Agent self, int nAngle) { return ((NpcBehaviac)self).TurnToPlace(nAngle); }));
			meta.RegisterMethod(1517759783, new CAgentMethod<bool, float, float, float>(delegate(Agent self, float nPosX, float nPosY, float nPosZ) { return ((NpcBehaviac)self).TurnToPos(nPosX, nPosY, nPosZ); }));
			meta.RegisterMethod(1252236948, new CAgentMethod<int, int>(delegate(Agent self, int nSkillCfgId) { return ((NpcBehaviac)self).SkillGetMaxRange(nSkillCfgId); }));
			meta.RegisterMethod(2638752981, new CAgentMethod<int, int>(delegate(Agent self, int nSkillCfgId) { return ((NpcBehaviac)self).SkillGetMinRange(nSkillCfgId); }));
			meta.RegisterMethod(1745332687, new CAgentMethod<bool, int>(delegate(Agent self, int nSkillCfgId) { return ((NpcBehaviac)self).SkillIsExist(nSkillCfgId); }));
			meta.RegisterMethod(2624220632, new CAgentMethod<bool, int>(delegate(Agent self, int nSkillCfgId) { return ((NpcBehaviac)self).SkillIsCooldown(nSkillCfgId); }));
			meta.RegisterMethod(2896640001, new CAgentMethod<bool, int>(delegate(Agent self, int nSkillCfgId) { return ((NpcBehaviac)self).SkillIsDo(nSkillCfgId); }));
			meta.RegisterMethod(1175311174, new CAgentMethod<bool, int, BehaviacSkillDoStageType>(delegate(Agent self, int nSkillCfgId, BehaviacSkillDoStageType eSkillDoStage) { return ((NpcBehaviac)self).SkillIsDoStage(nSkillCfgId, eSkillDoStage); }));
			meta.RegisterMethod(297963023, new CAgentMethodVoid<int, int>(delegate(Agent self, int nSkillCfgId, int nTime) { ((NpcBehaviac)self).SkillSetDurationTime(nSkillCfgId, nTime); }));
			meta.RegisterMethod(2135384195, new CAgentMethodVoid<int, int>(delegate(Agent self, int nSkillCfgId, int nTime) { ((NpcBehaviac)self).SkillSetAfterTime(nSkillCfgId, nTime); }));
			meta.RegisterMethod(2339559300, new CAgentMethodVoid<int, bool>(delegate(Agent self, int nSkillCfgId, bool bCooldown) { ((NpcBehaviac)self).SkillSetCooldown(nSkillCfgId, bCooldown); }));
			meta.RegisterMethod(3135348141, new CAgentMethodVoid<int, int>(delegate(Agent self, int nSkillCfgId, int nTime) { ((NpcBehaviac)self).SkillSetBeforeTime(nSkillCfgId, nTime); }));
			meta.RegisterMethod(838274261, new CAgentMethodVoid<int>(delegate(Agent self, int nSkillCfgId) { ((NpcBehaviac)self).SkillSetManualDo(nSkillCfgId); }));
			meta.RegisterMethod(3309503244, new CAgentMethod<bool, int>(delegate(Agent self, int nSkillCfgId) { return ((NpcBehaviac)self).SkillIsDoEnd(nSkillCfgId); }));
			meta.RegisterMethod(3663001320, new CAgentMethod<bool, int, int>(delegate(Agent self, int nSkillCfgId, int nNpcInstId) { return ((NpcBehaviac)self).SkillIsViewIn(nSkillCfgId, nNpcInstId); }));
			meta.RegisterMethod(2783428850, new CAgentMethod<bool, int, int>(delegate(Agent self, int nSkillCfgId, int nNpcInstId) { return ((NpcBehaviac)self).SkillIsMaxRangeIn(nSkillCfgId, nNpcInstId); }));
			meta.RegisterMethod(491690493, new CAgentMethod<bool, int, int>(delegate(Agent self, int nSkillCfgId, int nNpcInstId) { return ((NpcBehaviac)self).SkillIsMinRangeOut(nSkillCfgId, nNpcInstId); }));
			meta.RegisterMethod(2126763853, new CAgentMethod<bool, int>(delegate(Agent self, int nIdx) { return ((NpcBehaviac)self).DoSkill(nIdx); }));
			meta.RegisterMethod(904227883, new CAgentMethodVoid<int>(delegate(Agent self, int nSkillCfgId) { ((NpcBehaviac)self).SkillManualDo(nSkillCfgId); }));
			meta.RegisterMethod(2722795518, new CAgentMethodVoid<int>(delegate(Agent self, int nSkillCfgId) { ((NpcBehaviac)self).SkillResetDurationTime(nSkillCfgId); }));
			meta.RegisterMethod(1161600877, new CAgentMethodVoid<int>(delegate(Agent self, int nSkillCfgId) { ((NpcBehaviac)self).SkillResetAfterTime(nSkillCfgId); }));
			meta.RegisterMethod(641527450, new CAgentMethodVoid<int>(delegate(Agent self, int nSkillCfgId) { ((NpcBehaviac)self).SkillResetBeforeTime(nSkillCfgId); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());
			meta.RegisterMethod(4023451816, new CAgentMethodVoid<List<int>>(delegate(Agent self, List<int> taskArrayIntRef) { }) /* TaskArrayIntRef */);

			// TrapBehaviac
			meta = new AgentMeta(4012721731);
			AgentMeta._AgentMetas_[3146454028] = meta;
			meta.RegisterMethod(517719448, new CAgentMethodVoid<bool>(delegate(Agent self, bool bSuc) { ((TrapBehaviac)self).MapLevelEnd(bSuc); }));
			meta.RegisterMethod(333712300, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nBuffCfgId) { ((TrapBehaviac)self).NpcBuffAdd(nNpcInstId, nBuffCfgId); }));
			meta.RegisterMethod(1960930834, new CAgentMethod<int, int, int>(delegate(Agent self, int nNpcInstId, int nEffId) { return ((TrapBehaviac)self).AddNpcBodyEffect(nNpcInstId, nEffId); }));
			meta.RegisterMethod(1043635382, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nBuffCfgId) { ((TrapBehaviac)self).NpcBuffRemove(nNpcInstId, nBuffCfgId); }));
			meta.RegisterMethod(1252178389, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nTreatmentPercent) { ((TrapBehaviac)self).NpcTreatmentPercentInput(nNpcInstId, nTreatmentPercent); }));
			meta.RegisterMethod(1465201290, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nTreatmentVal) { ((TrapBehaviac)self).NpcTreatmentInput(nNpcInstId, nTreatmentVal); }));
			meta.RegisterMethod(3784053026, new CAgentMethod<int, List<int>>(delegate(Agent self, List<int> pArrayInt) { return ((TrapBehaviac)self).GetRandomIdxByWeight(pArrayInt); }));
			meta.RegisterMethod(2033743707, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((TrapBehaviac)self).IsNpcDead(nNpcInstId); }));
			meta.RegisterMethod(2728183447, new CAgentMethod<string>(delegate(Agent self) { return ((TrapBehaviac)self).GetCurCallTreeName(); }));
			meta.RegisterMethod(2045082202, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((TrapBehaviac)self).IsLevelNpcAllEnableByName0(nNameId); }));
			meta.RegisterMethod(3443252747, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((TrapBehaviac)self).GetLevelNpcAllDead0(nNameId); }));
			meta.RegisterMethod(3080141289, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((TrapBehaviac)self).IsLevelTrapAllEnableByName0(nNameId); }));
			meta.RegisterMethod(471432746, new CAgentMethod<bool, int>(delegate(Agent self, int nIdx) { return ((TrapBehaviac)self).GetEventParamBool(nIdx); }));
			meta.RegisterMethod(1398363131, new CAgentMethod<int, int>(delegate(Agent self, int nIdx) { return ((TrapBehaviac)self).GetEventParamInt(nIdx); }));
			meta.RegisterMethod(779082234, new CAgentMethod<string, int>(delegate(Agent self, int nIdx) { return ((TrapBehaviac)self).GetEventParamString(nIdx); }));
			meta.RegisterMethod(4133508887, new CAgentMethod<int, int, int>(delegate(Agent self, int nMin, int nMax) { return ((TrapBehaviac)self).GetRandomValByRange(nMin, nMax); }));
			meta.RegisterMethod(3645314284, new CAgentMethod<int>(delegate(Agent self) { return ((TrapBehaviac)self).GetPlayerNpcInstId(); }));
			meta.RegisterMethod(3163466376, new CAgentMethod<bool>(delegate(Agent self) { return ((TrapBehaviac)self).IsPlayerNpcDead(); }));
			meta.RegisterMethod(3372771259, new CAgentMethod<int>(delegate(Agent self) { return ((TrapBehaviac)self).GetFrameSynRunTime(); }));
			meta.RegisterMethod(2963145510, new CAgentMethodVoid<int>(delegate(Agent self, int nEffInstId) { ((TrapBehaviac)self).DelEffect(nEffInstId); }));
			meta.RegisterMethod(3718685615, new CAgentMethodVoid<int, bool>(delegate(Agent self, int nNameId, bool bEnable) { ((TrapBehaviac)self).SetLevelNpcEnableByName0(nNameId, bEnable); }));
			meta.RegisterMethod(1559481390, new CAgentMethodVoid<int, bool>(delegate(Agent self, int nNameId, bool nEnable) { ((TrapBehaviac)self).SetLevelTrapEnableByName0(nNameId, nEnable); }));
			meta.RegisterMethod(1672556066, new CAgentMethod<bool, int, int>(delegate(Agent self, int nNpcInstId, int nPercentVal) { return ((TrapBehaviac)self).IsNpcLastPercentHp(nNpcInstId, nPercentVal); }));
			meta.RegisterMethod(3109641221, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((TrapBehaviac)self).IsMonsterNpc(nNpcInstId); }));
			meta.RegisterMethod(3158467113, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((TrapBehaviac)self).IsBuildNpc(nNpcInstId); }));
			meta.RegisterMethod(96586450, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((TrapBehaviac)self).IsPlayerNpc(nNpcInstId); }));
			meta.RegisterMethod(3719375762, new CAgentMethod<bool, BehaviacCallType>(delegate(Agent self, BehaviacCallType eType) { return ((TrapBehaviac)self).IsCurCallType(eType); }));
			meta.RegisterMethod(1865017882, new CAgentMethod<bool, BehaviacGameEvent>(delegate(Agent self, BehaviacGameEvent eType) { return ((TrapBehaviac)self).IsTargetGameEvent(eType); }));
			meta.RegisterMethod(326959891, new CAgentMethodVoid<string, int, int, int, int, int>(delegate(Agent self, string sString, int nInt0, int nInt1, int nInt2, int nInt3, int nInt4) { ((TrapBehaviac)self).PrintLog(sString, nInt0, nInt1, nInt2, nInt3, nInt4); }));
			meta.RegisterMethod(1376336015, new CAgentMethod<int, int, string>(delegate(Agent self, int nCfgId, string sPointName) { return ((TrapBehaviac)self).AddNpcToMapByPoint(nCfgId, sPointName); }));
			meta.RegisterMethod(3067532362, new CAgentMethod<int, int, float, float, float, float, float, float>(delegate(Agent self, int nCfgId, float nPosX, float nPosY, float nPosZ, float nRotX, float nRotY, float nRotZ) { return ((TrapBehaviac)self).AddNpcToMapByPos(nCfgId, nPosX, nPosY, nPosZ, nRotX, nRotY, nRotZ); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { TrapBehaviac.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());
			meta.RegisterMethod(4023451816, new CAgentMethodVoid<List<int>>(delegate(Agent self, List<int> taskArrayIntRef) { }) /* TaskArrayIntRef */);

			// MapBehaviac
			meta = new AgentMeta(386043745);
			AgentMeta._AgentMetas_[4274058704] = meta;
			meta.RegisterMethod(517719448, new CAgentMethodVoid<bool>(delegate(Agent self, bool bSuc) { ((MapBehaviac)self).MapLevelEnd(bSuc); }));
			meta.RegisterMethod(333712300, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nBuffCfgId) { ((MapBehaviac)self).NpcBuffAdd(nNpcInstId, nBuffCfgId); }));
			meta.RegisterMethod(1960930834, new CAgentMethod<int, int, int>(delegate(Agent self, int nNpcInstId, int nEffId) { return ((MapBehaviac)self).AddNpcBodyEffect(nNpcInstId, nEffId); }));
			meta.RegisterMethod(1043635382, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nBuffCfgId) { ((MapBehaviac)self).NpcBuffRemove(nNpcInstId, nBuffCfgId); }));
			meta.RegisterMethod(1252178389, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nTreatmentPercent) { ((MapBehaviac)self).NpcTreatmentPercentInput(nNpcInstId, nTreatmentPercent); }));
			meta.RegisterMethod(1465201290, new CAgentMethodVoid<int, int>(delegate(Agent self, int nNpcInstId, int nTreatmentVal) { ((MapBehaviac)self).NpcTreatmentInput(nNpcInstId, nTreatmentVal); }));
			meta.RegisterMethod(3784053026, new CAgentMethod<int, List<int>>(delegate(Agent self, List<int> pArrayInt) { return ((MapBehaviac)self).GetRandomIdxByWeight(pArrayInt); }));
			meta.RegisterMethod(2033743707, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((MapBehaviac)self).IsNpcDead(nNpcInstId); }));
			meta.RegisterMethod(2728183447, new CAgentMethod<string>(delegate(Agent self) { return ((MapBehaviac)self).GetCurCallTreeName(); }));
			meta.RegisterMethod(2045082202, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((MapBehaviac)self).IsLevelNpcAllEnableByName0(nNameId); }));
			meta.RegisterMethod(3443252747, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((MapBehaviac)self).GetLevelNpcAllDead0(nNameId); }));
			meta.RegisterMethod(3080141289, new CAgentMethod<bool, int>(delegate(Agent self, int nNameId) { return ((MapBehaviac)self).IsLevelTrapAllEnableByName0(nNameId); }));
			meta.RegisterMethod(471432746, new CAgentMethod<bool, int>(delegate(Agent self, int nIdx) { return ((MapBehaviac)self).GetEventParamBool(nIdx); }));
			meta.RegisterMethod(1398363131, new CAgentMethod<int, int>(delegate(Agent self, int nIdx) { return ((MapBehaviac)self).GetEventParamInt(nIdx); }));
			meta.RegisterMethod(779082234, new CAgentMethod<string, int>(delegate(Agent self, int nIdx) { return ((MapBehaviac)self).GetEventParamString(nIdx); }));
			meta.RegisterMethod(4133508887, new CAgentMethod<int, int, int>(delegate(Agent self, int nMin, int nMax) { return ((MapBehaviac)self).GetRandomValByRange(nMin, nMax); }));
			meta.RegisterMethod(3645314284, new CAgentMethod<int>(delegate(Agent self) { return ((MapBehaviac)self).GetPlayerNpcInstId(); }));
			meta.RegisterMethod(3163466376, new CAgentMethod<bool>(delegate(Agent self) { return ((MapBehaviac)self).IsPlayerNpcDead(); }));
			meta.RegisterMethod(3372771259, new CAgentMethod<int>(delegate(Agent self) { return ((MapBehaviac)self).GetFrameSynRunTime(); }));
			meta.RegisterMethod(2963145510, new CAgentMethodVoid<int>(delegate(Agent self, int nEffInstId) { ((MapBehaviac)self).DelEffect(nEffInstId); }));
			meta.RegisterMethod(3718685615, new CAgentMethodVoid<int, bool>(delegate(Agent self, int nNameId, bool bEnable) { ((MapBehaviac)self).SetLevelNpcEnableByName0(nNameId, bEnable); }));
			meta.RegisterMethod(1559481390, new CAgentMethodVoid<int, bool>(delegate(Agent self, int nNameId, bool nEnable) { ((MapBehaviac)self).SetLevelTrapEnableByName0(nNameId, nEnable); }));
			meta.RegisterMethod(1672556066, new CAgentMethod<bool, int, int>(delegate(Agent self, int nNpcInstId, int nPercentVal) { return ((MapBehaviac)self).IsNpcLastPercentHp(nNpcInstId, nPercentVal); }));
			meta.RegisterMethod(3109641221, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((MapBehaviac)self).IsMonsterNpc(nNpcInstId); }));
			meta.RegisterMethod(3158467113, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((MapBehaviac)self).IsBuildNpc(nNpcInstId); }));
			meta.RegisterMethod(96586450, new CAgentMethod<bool, int>(delegate(Agent self, int nNpcInstId) { return ((MapBehaviac)self).IsPlayerNpc(nNpcInstId); }));
			meta.RegisterMethod(3719375762, new CAgentMethod<bool, BehaviacCallType>(delegate(Agent self, BehaviacCallType eType) { return ((MapBehaviac)self).IsCurCallType(eType); }));
			meta.RegisterMethod(1865017882, new CAgentMethod<bool, BehaviacGameEvent>(delegate(Agent self, BehaviacGameEvent eType) { return ((MapBehaviac)self).IsTargetGameEvent(eType); }));
			meta.RegisterMethod(326959891, new CAgentMethodVoid<string, int, int, int, int, int>(delegate(Agent self, string sString, int nInt0, int nInt1, int nInt2, int nInt3, int nInt4) { ((MapBehaviac)self).PrintLog(sString, nInt0, nInt1, nInt2, nInt3, nInt4); }));
			meta.RegisterMethod(1376336015, new CAgentMethod<int, int, string>(delegate(Agent self, int nCfgId, string sPointName) { return ((MapBehaviac)self).AddNpcToMapByPoint(nCfgId, sPointName); }));
			meta.RegisterMethod(3067532362, new CAgentMethod<int, int, float, float, float, float, float, float>(delegate(Agent self, int nCfgId, float nPosX, float nPosY, float nPosZ, float nRotX, float nRotY, float nRotZ) { return ((MapBehaviac)self).AddNpcToMapByPos(nCfgId, nPosX, nPosY, nPosZ, nRotX, nRotY, nRotZ); }));
			meta.RegisterMethod(1045109914, new CAgentStaticMethodVoid<string>(delegate(string param0) { MapBehaviac.LogMessage(param0); }));
			meta.RegisterMethod(2521019022, new CMethod_behaviac_Agent_VectorAdd());
			meta.RegisterMethod(2306090221, new CMethod_behaviac_Agent_VectorClear());
			meta.RegisterMethod(3483755530, new CMethod_behaviac_Agent_VectorContains());
			meta.RegisterMethod(505785840, new CMethod_behaviac_Agent_VectorLength());
			meta.RegisterMethod(502968959, new CMethod_behaviac_Agent_VectorRemove());
			meta.RegisterMethod(4023451816, new CAgentMethodVoid<List<int>>(delegate(Agent self, List<int> taskArrayIntRef) { }) /* TaskArrayIntRef */);

			AgentMeta.Register<behaviac.Agent>("behaviac.Agent");
			AgentMeta.Register<BaseBehaviac>("BaseBehaviac");
			AgentMeta.Register<NpcBehaviac>("NpcBehaviac");
			AgentMeta.Register<TrapBehaviac>("TrapBehaviac");
			AgentMeta.Register<MapBehaviac>("MapBehaviac");
			AgentMeta.Register<BehaviacGameEvent>("BehaviacGameEvent");
			ComparerRegister.RegisterType<BehaviacGameEvent, CompareValue_BehaviacGameEvent>();
			AgentMeta.Register<BehaviacCallType>("BehaviacCallType");
			ComparerRegister.RegisterType<BehaviacCallType, CompareValue_BehaviacCallType>();
			AgentMeta.Register<BehaviacNpcAttrType>("BehaviacNpcAttrType");
			ComparerRegister.RegisterType<BehaviacNpcAttrType, CompareValue_BehaviacNpcAttrType>();
			AgentMeta.Register<BehaviacNpcAttrValGetType>("BehaviacNpcAttrValGetType");
			ComparerRegister.RegisterType<BehaviacNpcAttrValGetType, CompareValue_BehaviacNpcAttrValGetType>();
			AgentMeta.Register<BehaviacNpcAttrValSetType>("BehaviacNpcAttrValSetType");
			ComparerRegister.RegisterType<BehaviacNpcAttrValSetType, CompareValue_BehaviacNpcAttrValSetType>();
			AgentMeta.Register<BehaviacSkillDoStageType>("BehaviacSkillDoStageType");
			ComparerRegister.RegisterType<BehaviacSkillDoStageType, CompareValue_BehaviacSkillDoStageType>();

			behaviac.Workspace.Instance.UseIntValue = true;
			return true;
		}

		public override bool UnLoad()
		{
			AgentMeta.UnRegister<behaviac.Agent>("behaviac.Agent");
			AgentMeta.UnRegister<BaseBehaviac>("BaseBehaviac");
			AgentMeta.UnRegister<NpcBehaviac>("NpcBehaviac");
			AgentMeta.UnRegister<TrapBehaviac>("TrapBehaviac");
			AgentMeta.UnRegister<MapBehaviac>("MapBehaviac");
			AgentMeta.UnRegister<BehaviacGameEvent>("BehaviacGameEvent");
			AgentMeta.UnRegister<BehaviacCallType>("BehaviacCallType");
			AgentMeta.UnRegister<BehaviacNpcAttrType>("BehaviacNpcAttrType");
			AgentMeta.UnRegister<BehaviacNpcAttrValGetType>("BehaviacNpcAttrValGetType");
			AgentMeta.UnRegister<BehaviacNpcAttrValSetType>("BehaviacNpcAttrValSetType");
			AgentMeta.UnRegister<BehaviacSkillDoStageType>("BehaviacSkillDoStageType");
			return true;
		}
	}
}
