// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

// -------------------
// Customized enums
// -------------------

public enum BehaviacGameEvent
{
	None,
	Npc_OnStart,
	Npc_OnDead,
	Map_OnGameStart,
	Map_OnNpcDead,
	Map_OnGameEnd,
	Trap_OnEnter,
	Trap_OnStay,
	Trap_OnExit,
	Buff_OnAdd,
	Buff_OnRemove,
	Buff_OnLayerInc,
	Buff_OnLayerDec,
	Buff_OnBuffAdd,
	Buff_OnBuffRemove,
}

public enum BehaviacCallType
{
	None,
	Update,
	Event,
}

public enum BehaviacNpcAttrType
{
	Hp = 1,
	Attack = 2,
	Weight = 3,
	Speed = 4,
	CostWeight = 5,
	Trun = 6,
	Durability = 7,
}

public enum BehaviacNpcAttrValGetType
{
	Base = 1,
	Percent = 2,
	All = 999,
}

public enum BehaviacNpcAttrValSetType
{
	Base = 1,
	Percent = 2,
}

public enum BehaviacSkillDoStageType
{
	BeforeEnter,
	BeforeUpdate,
	DurationEnter,
	DurationUpdate,
	AfterEnter,
	AfterUpdate,
	AfterExit,
}

